language: php

php:
    - 5.6

before_install:
    - sudo apt-get update > /dev/null

install:
    - sudo apt-get install -y --force-yes php5

before_script:
    - chmod +x bin/mysli
    - sudo cp bin/mysli /usr/bin

script:
    - mysli --self init
    - mysli pkg -e mysli.dev.testme
    - mysli test mysli.dev.testme
    - mysli test mysli.toolkit
