language: php
sudo: false

addons:
    apt:
        packages:
            - php5

php:
    - 5.6

before_script:
    - chmod +x bin/mysli
    - bin/mysli --self init
    - bin/mysli pkg -e mysli.dev.test

script:
    - bin/mysli test mysli.dev.test
    - bin/mysli test mysli.toolkit
