language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5

script: test.sh
