language: php

php:
  - 5.6

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes php5

before_script:
  - php ./packages/mysli/installer/src/php/stub.php -y

script:
  - cd private
  - ./dot pkgm -e mysli.dev.phpt
  - # Run tests...
  - ./dot phpt -t mysli.dev.phpt
  - ./dot phpt -t mysli.framework.cli
  - ./dot phpt -t mysli.framework.type
  - ./dot phpt -t mysli.framework.ym
  - ./dot phpt -t mysli.util.datetime
  - ./dot phpt -t mysli.util.i18n
  - ./dot phpt -t mysli.util.tplp
